### ISSUE TITLE
service crashes after updating to v2.93

### ISSUE THREAD

**Issue by Dusan44** [SirUli/victron-dbus-fronius-smartmeter#10]
Hi,

I am new to github and not familiar with python nor programming. I ran FroniusSmartmeter service installed through setup helper over 2 months without problem. After updating to venus 2.93 service started to crash.
I tried following:
root@raspberrypi2:/data/FroniusSmartmeter# svstat /service/FroniusSmartmeter
/service/FroniusSmartmeter: up (pid 9850) 1 seconds
root@raspberrypi2:/data/FroniusSmartmeter#  python3 /data/FroniusSmartmeter/fronius-smartmeter.py
Traceback (most recent call last):
  File "/data/FroniusSmartmeter/fronius-smartmeter.py", line 39, in <module>
    from vedbus import VeDbusService, VeDbusItemImport
ModuleNotFoundError: No module named 'vedbus'

svstat always retunns value less than 3 seconds and running fronius-smartmeter.py gives above error.

I do not want to go back to v 2.92. Can you give me any hint how to proceed. Thank you.

**Comment by pos-ei-don** [comment]
Same here. 

I did not find a solution, so I temporarily switched back to the original driver:
https://github.com/RalfZim/venus.dbus-fronius-smartmeter
This works, until this is fixed.

(but i am unshure, this may me a problem of the setuphelper itself. I had Problems with one other driver aswell.)

**Comment by SirUli** [comment]
That indeed looks odd. Thanks for the report, i'll take a look at it later!

**Comment by SirUli** [comment]
Fixed with v1.11
