### ISSUE TITLE
Please specify further how to manually set a persistent ip adress of a fronius inverter

### ISSUE THREAD

**Issue by dantehimself** [SirUli/victron-dbus-fronius-smartmeter#13]
### Summary

I run 2 Fronius Symo in my home network. They are not connected together, only connected to my network.
Only one of them has a Smartmeter connected to it. The inverter with the SmartMeter has the Inverter Number '2'. There are 2 existing IP-Adresses for this inverter, one for ethernet (cable), the other one for the WLAN interface.
The one without the SmartMeter has the inverter number '1'.

Sometimes it seems as if the script identifies the wrong inverter as the source for its SmartMeter Readings.

In the Readme, it is specified to start the script with --ip xxx.xxx.xxx.xxx - But where exactly can i specify this option?

### Issue Type

Feature Idea

**Comment by dantehimself** [comment]
should it be enough to add the param "--ip xxx.xxx.xxx.xxx" to the call in /data/FroniusSmartmeter/service/run?

I've tried it, but it looks as if it still does not run correctly

**Comment by SirUli** [comment]
I'll look into it - not sure if that is still implemented. Need to take another look.

**Comment by tonhart** [comment]
I had the same Problem: Two Fronius SmartMeter in the same Network.  Just add default='x.x.x.x' to the code. 

parser.add_argument(
        "--ip",
        help='IP Address of Smart Meter, leave empty to autodetect, specify "test" to use canned data',
        default='x.x.x.x'
    )

works out fine for me.

**Comment by dantehimself** [comment]
> I had the same Problem: Two Fronius SmartMeter in the same Network. Just add default='x.x.x.x' to the code.
> 
> parser.add_argument( "--ip", help='IP Address of Smart Meter, leave empty to autodetect, specify "test" to use canned data', default='x.x.x.x' )
> 
> works out fine for me.

Thank you SO MUCH tonhart! That works, now both of my Victron Systems start with the Fronius Smartmeter working :))

For clarification: The addition that tonhart mentioned has to be done in file /data/FroniusSmartmeter/fronius-smartmeter.py
