### ISSUE TITLE
Cannot get it to work with venusos 3.00~8

### ISSUE THREAD

**Issue by pos-ei-don** [SirUli/victron-dbus-fronius-smartmeter#6]
The output in the console alternates between "not connected" and just "w".

This directory is not present so i get not output there.
svstat /service/victron-dbus-fronius-smartmeter

The IP is detected correct.

The version of RalfZim works, but i wanted 
to use the update features of the setuphelper.

any hints what to do?

**Comment by SirUli** [comment]
I'll take a look, sorry was out for the holidays!

**Comment by SirUli** [comment]
@pos-ei-don can you check if v1.10 fixes your issue? Thanks!

**Comment by pos-ei-don** [comment]
@SirUli, thank you, now it works.

**Comment by SirUli** [comment]
Lovely - thanks for the feedback!
