### ISSUE TITLE
No Grid values when Multiplus is turned off

### ISSUE THREAD

**Issue by pos-ei-don** [SirUli/victron-dbus-fronius-smartmeter#8]
When my battery is empty, my Multiplus turmes off to reduce standby Power usage.
When this is the case, vrm Stopps showing grid measurements with this plugin.
Older (other) plugin kept sending values.

**Comment by SirUli** [comment]
That sounds a bit odd to me - my MP2 isn't even connected at the moment (changing my setup) and i still get Grid measurements into VRM and the Venus OS Console. The script is depending on the connected Fronius Inverter and Smartmeter - is this one turned off as well? The Fronius Inverter needs to continue to respond - otherwise the script doesn't work.

**Comment by pos-ei-don** [comment]
![Screenshot_20230115-095555](https://user-images.githubusercontent.com/1822533/212531920-bff8f176-9bc1-4c41-9307-b151b94117a2.png)

![Screenshot_20230115-095503](https://user-images.githubusercontent.com/1822533/212531932-5a586aad-3d39-4ddc-b641-b020df590a89.png)

Here are two Screenshots. The only difference is a multiplus in State "off".
I can reproduce it.

**Comment by SirUli** [comment]
Still odd i have to say. Can you check the log ``/var/log/FroniusSmartmeter/current`` for further details or failures?

**Comment by SirUli** [comment]
@pos-ei-don do you have further details on this one? Is this also the case when you use the version of Ralf Zimmermann?

**Comment by pos-ei-don** [comment]
Yes, I currently have this with the other driver aswell. So maybe this is an vrm issue or victron has a new value which is needed. My current workaround is to keep the multiplus on, even if the battery is empty. Not the best solution but it works.

**Comment by SirUli** [comment]
I would offer to do more debugging. How are you switching off the Multiplus? Did you configure the AES Mode?

**Comment by pos-ei-don** [comment]
I just switched it off using this Option (See Screenshot) 
I'm not using AES Mode. I cannot switch it off currently to debug it further as 
I am currently completly detached from grid. Maybe I can try again in a weeck ot two. 

![Screenshot_20230305-215524](https://user-images.githubusercontent.com/1822533/222985529-56a98859-f252-4819-b86d-ae915aa8cbbd.png)

**Comment by SirUli** [comment]
I just tried that and for me the values continued to be available. Will be interesting what your test will show (especially in the logs).

**Comment by pos-ei-don** [comment]
Thank you for trying. I just tested and can reproduce it.
Unfortunately, I have no idea how to access Logs. I did have a look for log Files, but it seems they are hiding.

**Comment by SirUli** [comment]
I pushed a change to the README yesterday to help with debugging: See [here](https://github.com/SirUli/FroniusSmartmeter#service-logs). Do you see anything in there?

Thanks in advance!

**Comment by pos-ei-don** [comment]
unfortunately this log is almost empty, doesn't seem to help a lot.
is there a parameter to increase verbosity?

@400000006405e9cf2f3428ec FroniusSmartmeter/setup: adding FroniusSmartmeter/setup to reinstallScriptsList
@400000006405e9cf33f0322c FroniusSmartmeter/setup: completed
@400000006405ea1527b2ae7c *** CCGX booted (0) ***

The values in the gx Console are still updated, when the Multiplus (3 phase system) is off.
I did not have this problem when using a 1phase system.
I think that this is either a VRM-Problem or there is a (new?) dbus-Parameter missing

**Comment by SirUli** [comment]
Hi @pos-ei-don i finally understand the problem and I'm very sorry for my wrong first investigation. You are right, as soon as the MP2 is turned off using the switch in the remote console the VRM doesn't show any values. I'm still digging through the system if I can find anything but so far I wasn't successful.

**Comment by SirUli** [comment]
I believe this is a VRM issue which i cannot solve. Unfortunately i will have to close this here - i don't see anything possible.
